### SIGN UP USER

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "username": "user_8",
  "password": "User1pass!",
  "confirmPassword": "User1pass!"
}


### SIGN IN USER

POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
  "username": "user_2",
  "password": "User1pass!"
}


### SIGN OUT USER
POST http://localhost:3000/api/auth/signout